#cloud-config
users:
  - default
  - name: multipass-compose
    plain_text_passwd: secret
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups:
      - users
      - admin
    shell: /bin/bash
    lock_passwd: false
package_update: true
package_upgrade: true
packages:
  - avahi-daemon
ssh_pwauth: true
