#cloud-config
users:
  - default
  - name: multipass-compose
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups:
      - users
      - admin
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC1j/ij8hqt6j5VHbv940clm9Vbkv5KMShp+csg5lFxPszKemh4KvvALCxY8njfMe/9dogTi9IhtJAg9SsDud4keC8/1AkfuPKWMWjPFBOhBsfBPXcAHh3X2eZmtHCNOfzHS0jIh564JVz/K7qFXhcShMMaMa8S0JncaLyCVTPolktFdC99FrOmU18YGR1/SWrImX1yO462FnSnkSmXjYxLqRcVSGdDEmEuTBVtfiVgJedQSt7l0jpzPXu+yBk86XSFJZ2UMtZ23yJPucs7D+uJ4CS2dNgdDhRvmX59K5nzIBX+iRg4wCv5kXRHaJgiw2QBEZNQhyW/nhfwDry1ivoIu2rxz8flO6yeJdBX7WsZpYguOc9/MfDBYBzqkKsqec3W08ueW554QQxH90iIw2z4Ov8EpgFF1hp9HYumNAinNcaZ3kjc947xezA7almP4hU/frN+YMk+uiODRhyGGnFMDjRfVPeTnrhGiaM+LUUQyGMSYJ7K1E0MdXNV3d4x31s=
package_update: true
package_upgrade: true
packages:
  - avahi-daemon
